### ISSUE TITLE
Error on Ubuntu 18.04

### ISSUE THREAD

**Issue by eddelbuettel** [Enchufa2/bspm#15]
When using the same setup as for Debian testing and Ubuntu 20.04, I see a failure with 18.04.  This may of course come from the Python stack, or an older version of the packages.

Issue:

```r
Loading required package: utils
Tracing function "install.packages" in package "utils"
> install.packages("digest")
Error: cannot connect to the system package manager
> 
````

Packages used:

```sh
root@d48089f64dd2:/# dpkg -l r-cran-bspm python3-apt python3-dbus python3-gi python3 | cut -c-80 | cut -c-48
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/
|/ Err?=(none)/Reinst-required (Status,Err: uppe
||/ Name           Version          Architecture
+++-==============-================-============
ii  python3        3.6.7-1~18.04    amd64       
ii  python3-apt    1.6.5ubuntu0.3   amd64       
ii  python3-dbus   1.2.6-1          amd64       
ii  python3-gi     3.26.1-2ubuntu1  amd64       
ii  r-cran-bspm    0.3.4.1-1.1804.1 all         
root@d48089f64dd2:/# 
```

18.04 would be a "nice to have" but if `python3-apt` is too old so be it.   On the other hand, Debian and Ubuntu had Python tooling against `apt` for many many years so it clearly worked then, but maybe something is just different enough to cause this. Maybe it is something simple though and you can get to it.

For comparison, on a focal ("20.04") system I see

```sh
edd@rob:~/git/rocker/r-bspm/bionic(master)$ dpkg -l r-cran-bspm python3-apt python3-dbus python3-gi python3 | cut -c-80 | cut -c-49
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/H
|/ Err?=(none)/Reinst-required (Status,Err: upper
||/ Name           Version              Architect
+++-==============-====================-=========
ii  python3        3.8.2-0ubuntu2       amd64    
ii  python3-apt    2.0.0ubuntu0.20.04.1 amd64    
ii  python3-dbus   1.2.16-1build1       amd64    
ii  python3-gi     3.36.0-1             amd64    
ii  r-cran-bspm    0.3.4.1-1.2004.1       all      
edd@rob:~/git/rocker/r-bspm/bionic(master)$ 
```

and there a few internal changes with the apt (programming) library around release 2.0 (and 1.9 testing it).

**Comment by Enchufa2** [comment]
Branch `fix/python36` works on Ubuntu 18.04 as a docker container (as you can see [here](https://github.com/Enchufa2/bspm/actions/runs/220974311)), but it fails as a regular user, via DBus. APT returns `installArchives() failed`, and journalctl shows `dpkg: error: PATH is not set`. Any idea?

**Comment by eddelbuettel** [comment]
Will take a look.  Can't immediatly think of why it would pass for root but not for user.  Unless something simple gets in the way -- maybe a command is only in `/usr/sbin` and the normal mortal does not see that?

**Comment by eddelbuettel** [comment]
"Works for me" in a freshly rebuilt Docker container, as root and user.  How do you generate the error?

**Comment by Enchufa2** [comment]
"As user" you mean with `sudo`, right? The error arises only via DBus. I installed Ubuntu 18.04 in VirtualBox, installed R and the package, opened a regular R session, and that's what I get. Someone is not setting the PATH properly. My bet is that it must be either systemd's or dbus' fault.

**Comment by eddelbuettel** [comment]
Yes, as opposed to as root.  In Docker in both cases. And calling `sudo` because that is what `bspm` does.

I would need a more complete "recipe" to reproduce.  At present I cannot help you.

**Comment by Enchufa2** [comment]
Update: I printed `os.environ` when launched as a DBus service both on Ubuntu 20.04 and 18.04, same content. So the issue must be in python3-apt. I'll look into the changelog to see if there's any clue there, and whether there's any possible workaround for such an old version.

Question: is it possible to install python3-apt v2 into Ubuntu 18.04 by reasonable means?

**Comment by eddelbuettel** [comment]
Not sure.  I did a little bit of programming around the APT C++ API and my general understanding is that the whole apt nexus is quite involved and cohesive.  I don't think we'd "win" by grafting the new APT onto on older release.

If you have some standard Python scripts I could run (outside of what is packages in bspm) that may help.  Right now it is a little difficult to disentangle.

**Comment by Enchufa2** [comment]
You are right, Ubuntu 18.04 is tied to that version of python3-apt, as well as apt and dpkg. I didn't find anything relevant in python-apt's changelog, so my guess is that the bug is in libapt or dpkg. I don't think there's much we can do about it, so I've changed the dispatch logic to prioritise `sudo`, if enabled via `options(bspm.sudo=TRUE)`, over DBus calls. In this way, at least a desktop user can bypass DBus and workaround any issue or incompatibility.

If you find any better solution, I'd be happy to revisit this. I've managed at least to reproduce the _remaining_ issue in a docker container as follows:

```
$ docker run --rm -it ubuntu:18.04
$ apt update && apt install -y git python3-apt
$ git clone https://github.com/Enchufa2/bspm
$ env -i bspm/inst/service/bspm.py install Rcpp
...
dpkg: error: PATH is not set
E:Sub-process /usr/bin/dpkg returned an error code (2)
Traceback (most recent call last):
  File "bspm/inst/service/bspm.py", line 131, in <module>
    run_as_root(args)
  File "bspm/inst/service/bspm.py", line 107, in run_as_root
    pkgs = getattr(backend, args.cmd)(PREF, args.pkg, EXCL)
  File "/root/bspm/inst/service/backend/apt.py", line 54, in install
    return operation("mark_install", prefixes, pkgs, exclusions)
  File "/root/bspm/inst/service/backend/apt.py", line 48, in operation
    cache.commit(aprogress)
  File "/usr/lib/python3/dist-packages/apt/cache.py", line 681, in commit
    raise SystemError("installArchives() failed")
SystemError: installArchives() failed
```

The last command launches the script in a clean environment, similar to what the DBus service gets, and it runs just fine on ubuntu:20.04.

**Comment by Enchufa2** [comment]
Oh, wait a moment... I'm accustomed to the fact that, in Fedora, `/bin`and `/sbin` are just links to `/usr/bin` and `/usr/sbin`. So I tried setting `PATH=/usr/bin:/usr/sbin` and failed, but:

```
$ env -i PATH=/usr/bin:/usr/sbin:/bin:/sbin bspm/inst/service/bspm.py install Rcpp
```

succeeds! If this works also in the VirtualBox machine, I'm including that as a workaround in `bspm.py`.

**Comment by Enchufa2** [comment]
It works! If you have a moment to double-check this, it would be helpful. And if there are no further issues or comments, I can roll out a new release to CRAN.

**Comment by eddelbuettel** [comment]
Excellent news.  I'd roll out a new release as this already worked for me before you expanded `$PATH`.

**Comment by Enchufa2** [comment]
On CRAN now.

**Comment by eddelbuettel** [comment]
I expected as much as already updated three containers :)   `rocker/r-bspm` now comes in tasty flavors `testing`, `18.04` and `20.04`.
