### ISSUE TITLE
Code is against the CRAN Repository Policy

### ISSUE THREAD

**Issue by jimhester** [Enchufa2/bspm#18]
Just a FYI, the code in https://github.com/Enchufa2/bspm/blob/9d3a52c35eba3c65a668d753cdc9c80de43313dd/R/integration.R#L30-L34 is plainly against [CRAN policies](https://cran.r-project.org/web/packages/policies.html)

> - A package must not tamper with the code already loaded into R: any attempt to change code in the standard and recommended packages which ship with R is prohibited. Altering the namespace of another package should only be done with the agreement of the maintainer of that package.

If anyone at CRAN happens to notice you will have to change it.

**Comment by Enchufa2** [comment]
Thanks, Jim, for taking the time to review the package. We know the policies, and we had our doubts, but I certainly wouldn't say "plainly against" the policy. "Tamper" is a big word. Replacing a function in a namespace is clearly tampering. This case is quite different though: it requires an action from the user (the user knows what this is for, and must explicitly call the function to enable this functionality), its effects are clearly visible (the message from the `trace` function is visible), and the functionality of `install.packages` is not modified at all. So I would say that this use case is more aligned with the exceptions that are permitted for writing files with user permission. But of course, discussions here are pointless. If CRAN disagrees, we'll certainly know. :)

**Comment by jimhester** [comment]
The call to trace is literally changing code in a standard and recommended package, it is pretty black and white.

An easy to implement alternative that _would_ allow you to be compliant with CRAN would be to export a `install.packages()` function from bspm that calls `bspm::install_sys()`, then passes `...` down to `utils::install.packages()`. Then users can simply attach the bspm package, and call `install.packages()` or call `bspm::install.packages()` rather than `utils::install.packages()` for the extra functionality.

**Comment by Enchufa2** [comment]
Thanks, we'll have this in mind if CRAN complains.
