### ISSUE TITLE
Error on Ubuntu 20

### ISSUE THREAD

**Issue by jaum20** [Enchufa2/bspm#20]
install packages is not working:

```
library(bspm)
enable()
install.packages('rgdal')
```

> Install system packages...
> Reading package lists... Done
> Building dependency tree        
> Reading state information... Done
> Ign https://mint.itsbrasil.net/packages ulyana InRelease                       
> Hit https://mint.itsbrasil.net/packages ulyana Release                         
> Hit https://ubuntu.itsbrasil.net/ubuntu focal InRelease                        
> Hit https://ubuntu.itsbrasil.net/ubuntu focal-updates InRelease                
> Hit https://ubuntu.itsbrasil.net/ubuntu focal-backports InRelease              
> Hit http://archive.canonical.com/ubuntu focal InRelease                        
> Hit http://ppa.launchpad.net/papirus/papirus/ubuntu focal InRelease            
> Hit https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease       
> Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]      
> Fetched 107 kB in 6s (11.2 kB/s)                                               
> Reading package lists... Done    
> Building dependency tree          
> Reading state information... Done
> Fetched 0 B in 0s (0 B/s)                                                      

But it doesn't install the package:

`library(rgdal)`

> Error in library(rgdal) : there is no package called ‘rgdal’

R version 4.0.2 (2020-06-22)

**Comment by Enchufa2** [comment]
Please, provide the output of `sessionInfo()`, `.libPaths()` and, in Bash, `apt search rgdal`.

**Comment by Enchufa2** [comment]
Ok, I found the issue. You added the repo for R 4.0, but Rutter's c2d4u, right? Then you have R packages in the repos that are built against R 3.6.3, and thus they can't be installed. However, the APT call should fail and `install.packages` should continue from CRAN. This issue is solved in the commit above.

**Comment by jaum20** [comment]
Thank you!

**Comment by eddelbuettel** [comment]
Sorry -- didn't see this earlier.  We're behind documenting more clearly what one needs but you can 
- look at my [Dockerfile setups for Ubuntu 18.04 + 20.04 as well as Debian testing](https://github.com/rocker-org/rocker/tree/master/r-bspm)
- run the corresponding containers `rocker/r-bspm` with tags `18.04`, `20.04`, and `testing`

All are set up to the corresponding repos and for the Ubuntu ones the (new) Rutter PPA is enabled.  Demo is in the [blog post](http://dirk.eddelbuettel.com/blog/2020/08/26#029_introducing_bspm)
