### ISSUE TITLE
Ability to turn bus off again?

### ISSUE THREAD

**Issue by eddelbuettel** [Enchufa2/bspm#21]
I have been looking into build on top of bspm and the existing containers for more CI work, but something keep popping up that I don't quite understand.   It appears to be related to running `R CMD check ...` after having relied on `bspm` to install a binary.  So I am wondering if we need to "turn it off again" or can otherwise circumvent the issues.  

One way to replicate is to use one of my containers and repos (which I used just because I had them here).  E.g.

- launch Docker in repo (or `/tmp`) with tarball to be tested; I just used `anytime` because I test it often enough
- install packages `Rcpp` and `BH` via `bspm`
- run check, see weird output

```sh
$ docker run --mt -ti -v ${PWD}:/work -w work -u 1000:1000 rocker/r-bspm:20.04 bash
docker@....:/work$ install.r Rcpp BH 
(loaded the methods namespace)   
Loading required package: utils                                                                          
Tracing function "install.packages" in package "utils"  
[....]
Unpacking r-cran-rcpp (1.0.5-1cran1.2004.0) ...                                                          
Setting up r-cran-bh (1.72.0-3-1cran1.2004.0) ...                                                        
Setting up r-cran-rcpp (1.0.5-1cran1.2004.0) ...                                                         
docker@69da05f16843:/work$ _R_CHECK_FORCE_SUGGESTS_=FALSE R CMD check --no-manual --no-vignettes anytime_0.3.9.tar.gz 
Loading required package: utils                                                                          
Tracing function "install.packages" in package "utils"
* using log directory ‘/work/anytime.Rcheck’  
[...]
* checking for missing documentation entries ... WARNING
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking for code/documentation mismatches ... WARNING
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
* checking Rd \usage sections ... NOTE
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
The \usage entries for S3 methods should use the \method markup and not
their full name.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
[...]
* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 4 WARNINGs, 7 NOTEs
See
  ‘/work/anytime.Rcheck/00check.log’
for details.


docker@...........:/work$ 
```

Any idea?

**Comment by Enchufa2** [comment]
It doesn't seem to be related to bspm. I've:

- disabled bspm by removing the corresponding line in `/etc/R/Rprofile.site`;
- installed Rcpp and BH via `sudo apt install`;
- executed `R CMD check`;

and I've got the same weird messages.

**Comment by Enchufa2** [comment]
Is `systemd` a hard dependency of `r-cran-bspm`? A solution would be to set it as a recommended one, which I believe would be installed by default, but not in this docker (consequently, `python3-dbus` and `python3-gi` should be recommended too).

**Comment by Enchufa2** [comment]
BTW, I see

```
* checking whether the namespace can be loaded with stated dependencies ... NOTE
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
Warning in system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
```

which seems to be related to [this](https://github.com/eddelbuettel/anytime/issues/114). So definitely nothing to do with bspm. It's R who calls `timedatectl`, and

```
$ timedatectl 
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
```

that's what creates the messages.

**Comment by eddelbuettel** [comment]
Good catch on `timedatectl`. I had tested earlier and convinced myself that this was due to the `bspm` additions, which could of course also be from `systemd` and friends.  And don't get me wrong, it is also because `bspm` is so awesome that I am in this pothole as I would love the awesomeness without sideeffects.

**Comment by eddelbuettel** [comment]
And confirmed. I didn't do my homework well enough -- the same error happens "one container up" in `rocker/r-ubuntu:20,04'.  My bad.  It really seems like a `timedatectl` issue on Ubuntu only and not on Debian (where more of my containers reside).

I close this.

**Comment by Enchufa2** [comment]
No problem. FWIW, even if you can prevent R from calling `timedatectl`, I think it may be a good idea to set `python3-dbus` and `python3-gi` as recommended in bspm's packaging, so that these docker images would be smaller without the DBUS and systemd stuff.

**Comment by eddelbuettel** [comment]
So `timedatectl` is part of `systemd` and already present "one container up from us". So I either need to rename it in the container (ugh) or look more closely at the R code to avoid running it.  Which *may* be as easy as setting `TZ` in the first place.

Base R code is in `src/library/base/R/datetime.R` and simply starts with `timedatectl` as `## First try timedatectl: should work on any modern Linux` and `## as part of systemd (and probably nowhere else)`.  

Doing `export TZ=UTC` is all I needed.

Now, as for your suggestion to run without the `dbus` and `gi` packages:  I was under the impression I _needed_ them for `bspm` to function.  The container is built for `bspm`.  Hence their presence.  What am I missing?




modern systems should have it

**Comment by eddelbuettel** [comment]
Also:

```sh
edd@rob:~/git/anytime(master)$ docker images |grep "^rocker.*20.04"
rocker/r-bspm                        20.04               f2340b2f2e9e        11 days ago         700MB
rocker/r-ubuntu                      20.04               8703fed02c01        3 weeks ago         669MB
rocker/r-rspm                        20.04               2711ee6b1c2d        2 months ago        784MB
edd@rob:~/git/anytime(master)$ 
```

Added size no real concern for me here.  We start with 670mb to make R possible.  Adding 30mb to make package installation easy(er) is so worth it.

**Comment by eddelbuettel** [comment]
For what it is worth, I now added the `TZ` variable and rebuilt `rocker/r-ubuntu:{18.04,20.04}` and the `rocker/r-bspm:{18.04,20.04}` that sit on top of them and all is well.   Thanks for spotting that -- I failed 'Debugging 101' of reading the error message closely enough.

**Comment by Enchufa2** [comment]
> So `timedatectl` is part of `systemd` and already present "one container up from us". 

Too bad, because these are mostly useless in a docker container.

> Doing `export TZ=UTC` is all I needed.

Great.

> Now, as for your suggestion to run without the `dbus` and `gi` packages: I was under the impression I _needed_ them for `bspm` to function. The container is built for `bspm`. Hence their presence. What am I missing?

They are needed when systemd is PID 1, in which case the system bus is used. But docker containers don't have either a system bus nor systemd running, so the only package always required is the connector to the package manager, `python3-apt` in this case.

**Comment by eddelbuettel** [comment]
Thanks for the reminder.  So the _package_ remains entirely correct in dependending on them, and in the container I will simply live with the extra bit of fluff as I value the consistency across within container / normal use outside installations.

**Comment by Enchufa2** [comment]
> > So `timedatectl` is part of `systemd` and already present "one container up from us".

Mmmh... I checked that

```
$ docker run --rm -it ubuntu:focal
# busctl
bash: busctl: command not found
# apt install --no-install-recommends software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ca-certificates dbus dbus-user-session dconf-gsettings-backend dconf-service distro-info-data gir1.2-glib-2.0
  gir1.2-packagekitglib-1.0 glib-networking glib-networking-common glib-networking-services gpg gpgconf gsettings-desktop-schemas
  iso-codes libapparmor1 libappstream4 libargon2-1 libassuan0 libbrotli1 libcap2 libcap2-bin libcryptsetup12 libdbus-1-3 libdconf1
  libdevmapper1.02.1 libelf1 libexpat1 libgirepository-1.0-1 libglib2.0-0 libglib2.0-bin libglib2.0-data libgssapi-krb5-2
  libgstreamer1.0-0 libicu66 libip4tc2 libjson-c4 libk5crypto3 libkeyutils1 libkmod2 libkrb5-3 libkrb5support0 liblmdb0 libmpdec2
  libpackagekit-glib2-18 libpam-systemd libpolkit-agent-1-0 libpolkit-gobject-1-0 libproxy1v5 libpsl5 libpython3-stdlib
  libpython3.8-minimal libpython3.8-stdlib libreadline8 libsoup2.4-1 libsqlite3-0 libssl1.1 libstemmer0d libxml2 libyaml-0-2
  lsb-release mime-support openssl packagekit policykit-1 python-apt-common python3 python3-apt python3-certifi python3-chardet
  python3-dbus python3-gi python3-idna python3-minimal python3-pkg-resources python3-requests python3-requests-unixsocket python3-six
  python3-software-properties python3-urllib3 python3.8 python3.8-minimal readline-common systemd systemd-sysv systemd-timesyncd tzdata
...
After this operation, 132 MB of additional disk space will be used.
```

So [this](https://github.com/rocker-org/rocker/blob/master/r-ubuntu/focal/Dockerfile#L20) is what installs systemd and timedatectl, which I believe is needed for `add-apt-repository`. Maybe if there's another way to add repos, you could save those 132 MB in rocker/r-ubuntu, and thus in rocker/r-bspm.

**Comment by eddelbuettel** [comment]
:man_shrugging: 

Very nice sleuthing on your part, but after 25+ with Debian I just don't believe in second-guessing the package manager.  So `add-apt-repository` has a cost.  Fine.  My goal is not to create 50mb Alpine containers that then break in other unexpected places.

I _want_ people to be able to add repos easily.  Having had the Rutter PPAs for 10+ years, I think the single biggest "problem" is that that README.md is still too dense and technical (ever after I nudged Michael a couple of times).   `add-apt-repository` is a convenient and powerful command that also deal with the GPG keys and whatnot.  Yes, the footprint may be big.  I just don't care that much.  My BH package for R is larger still (which is another crazy issue, but just to show that we use disk space in other spots too...)

**Comment by eddelbuettel** [comment]
And its a weird world.  `r-ubuntu`, which `r-bspm` uses, was meant for 'R on Ubuntu plus PPA'.  It is still smaller than the `r-base` aka `rocker/r-base` container because of whatever Ubuntu already did to trim fat of the basic R-on-testing I do in `r-base`.  At R 4.0.2 `r-base` comes in at 824mb right now which is way more than the 701mb and 638mb for 20.04 and 18.04, respectively, of bspm.  The `rocker/r-bspm:testing` building on Debian is currently at 822mb where as r-base, most recent build, is at 750mb.  I can live with that difference.  

But again, really appreciate you dug in. That was exactly the right angle to look at.

**Comment by Enchufa2** [comment]
This is like refactoring code: when you start digging, it's like an addiction. :) But in the wider picture, I agree life is certainly too short to waste time doing everything `add-apt-repository` does (forgot about the GPG stuff and all that, which is a pain...) for a few MB.

**Comment by eddelbuettel** [comment]
Came across this the other day which is pure gold and your first point:  

https://www.youtube.com/watch?v=AbSehcT19u0
