### ISSUE TITLE
Package dependencies of unavailable package

### ISSUE THREAD

**Issue by tjtnew** [Enchufa2/bspm#23]
When installing a package that is unavailable in COPR (in this instance `vdiffr`), all dependent packages are then installed from CRAN even if they are available on COPR.  I assume this is related to #14 so probably intended, but wanted to check to make sure?

**Comment by Enchufa2** [comment]
Yes, it's #14. But if the expectation is another one, I could implement the installation of dependencies from the system, regardless whether the requested packages are available or not. It's pretty straightforward. I would like to keep `bspm` simple, so it would be optional and disabled by default. But I could even make this the default in cran2copr.

BTW, I'm not sure why `vdiffr` is not available. Probably some missing dependency. I have to check.

**Comment by tjtnew** [comment]
I think it would be nice for cran2copr but only if east. I know what you mean for about freetypeharfbuzz; it was a surprise when I saw it was downloading from lionel's GitHub repo!

**Comment by Enchufa2** [comment]
Keeping this open until the change arrives cran2copr.

**Comment by Enchufa2** [comment]
v0.3.6 on CRAN and on cran2copr. You can fetch the update by running

```
sudo dnf update --refresh R-CoprManager
```

**Comment by tjtnew** [comment]
Great - works a treat!
