### ISSUE TITLE
Error message when package not available

### ISSUE THREAD

**Issue by tjtnew** [Enchufa2/bspm#25]
Only a minor issues but would it be possible to handle the error message when a package is not available from both copr and CRAN?  Currently you get a dbus error rather than an informative message (e.g. `package not available`)
```r
install.packages("packagedoesnotexist")
Install system packages...

Error in install.packages : dbus: Call failed: wrapper() missing 1 required positional argument: 'pid'
```

**Comment by Enchufa2** [comment]
Thanks, will do.

**Comment by tjtnew** [comment]
Quick as always 👍

**Comment by Enchufa2** [comment]
I'll wait a little bit to send a new release to CRAN, but the pre-release is now built on Copr.
