### ISSUE TITLE
Autoconfigure the rpm vs deb choice?

### ISSUE THREAD

**Issue by eddelbuettel** [Enchufa2/bspm#3]
Having to explicitly pass the parameters is tedious.  Would you be open to a simple PR (I can test at length on Ubuntu/Debian) to pick the parameter if on Debian?

I recently looked into some simple 'where am I' heuristics and one such (shell) script is

```sh
#!/bin/sh
#
# cf https://unix.stackexchange.com/a/6348/10300 plus minor mods

if [ -f /etc/debian_version ]; then
    # Older Debian/Ubuntu/etc.
    OS=Debian
    VER=`cat /etc/debian_version`
elif type lsb_release >/dev/null 2>&1; then
    # linuxbase.org
    OS=`lsb_release -si`
    VER=`lsb_release -sr`
elif [ -f /etc/lsb-release ]; then
    # For some versions of Debian/Ubuntu without lsb_release command
    . /etc/lsb-release
    OS=$DISTRIB_ID
    VER=$DISTRIB_RELEASE
elif [ -f /etc/os-release ]; then
    # freedesktop.org and systemd
    . /etc/os-release
    OS=$NAME
    VER=$VERSION_ID
#elif [ -f /etc/SuSe-release ]; then
    # Older SuSE/etc.
#    ...
#elif [ -f /etc/redhat-release ]; then
    # Older Red Hat, CentOS, etc.
#    ...
else
    # Fall back to uname, e.g. "Linux <version>", also works for BSD, etc.
    OS=`uname -s`
    VER=`uname -r`
fi

echo $OS:$VER
```

This should be more than sufficient for our case. At recent RHub builds given
- `fedora-clang-devel` was selected it showed `Fedora:31`, 
- `debian-clang-devel` was selected it showed `Debian:bullseye/sid`.  

More than enough for our needs.

**Comment by Enchufa2** [comment]
Definitely. I was already working in that direction. See the devel branch, where I removed the need to pass the D-Bus locations (because basically they're always in the same places in all distributions).

Now, the prefix is still needed. This could be automatically chosen with this distro detection mechanism, but at the same time the user needs to be able to override it. Also, we need #1, because e.g. in Debian you have `r-cran-` as well as `r-bioc-`, right?

**Comment by eddelbuettel** [comment]
Great -- and one step at a time.  The forced arguments are "stoooopid" because they can be derived. Let me know if you want me to help.

And yes, there is in `r-cran-*` and well as quite a few `r-bioc-*` and less than a handful each of `r-omegahat-*` and `r-other-*`.  Maybe my RcppAPT will be of use as it can find all those among reverse dependencies of `r-base-core` ?

There are are other improvements we should aim for---writing below `/usr` is a no-no for a non-system package but it sounds like you are moving that way already or did I misread this?

**Comment by Enchufa2** [comment]
> Great -- and one step at a time. The forced arguments are "stoooopid" because they can be derived. Let me know if you want me to help.
> 
> And yes, there is in `r-cran-*` and well as quite a few `r-bioc-*` and less than a handful each of `r-omegahat-*` and `r-other-*`. Maybe my RcppAPT will be of use as it can find all those among reverse dependencies of `r-base-core` ?

You mean to discover those prefixes at install time? I was thinking about hardcoding them for different distros with an optional parameter to override them. Or are they gonna change a lot?

> There are are other improvements we should aim for---writing below `/usr` is a no-no for a non-system package but it sounds like you are moving that way already or did I misread this?

Writing to /usr and /etc is still needed for the system service to work. What I did is to hardcode those paths, because they don't change from distro to distro, and issue a warning if those files couldn't be installed (but that's just for development purposes).

This really *needs* to be a system package, we cannot escape that, because we need something with root privileges talking to R. No system daemon can live under /home.

**Comment by eddelbuettel** [comment]
> hardcoding them

Ouch. That changes a little. I would recommend against a static fixed list...  Also, someone may have local packages etc pp.  

I was thinking that maybe `python3-{dnf,apt}` can report them to us.  Maybe run a query at package load, or when we enable?  

The `/usr/` and `/etc` writes are indeed icky so maybe this will "simply" become a system package. I will go that route in Docker first.

**Comment by Enchufa2** [comment]
> > hardcoding them
> 
> Ouch. That changes a little. I would recommend against a static fixed list... Also, someone may have local packages etc pp.
> 
> I was thinking that maybe `python3-{dnf,apt}` can report them to us. Maybe run a query at package load, or when we enable?

The main point of the prefix is to prevent users from installing (or removing) *any* package in the system, including... well, r-base. I don't see a good way to list all R packages via dnf or apt if you don't know what's the prefix a priori (because there are hardcoded well-known defaults or because the rpm/deb packager knows and sets it).

> The `/usr/` and `/etc` writes are indeed icky so maybe this will "simply" become a system package. I will go that route in Docker first.

But that's for end-user systems. Inside docker, you are already root, and you don't need the service at all. That's what the last update does: if it detects that you are root, it calls the package manager directly via python3-{dnf,apt}, without starting any service (which wouldn't work anyway, because there's generally no system bus nor systemd in a container).

**Comment by eddelbuettel** [comment]
We are talking to `apt` and `dnf` so we should take advantage of it.  Here is what I once did avoiding `python3-apt`:

```r
R> library(RcppAPT)
R> revdep <- reverseDepends("r-base-core")
R> head(revdep)
          package        version
1  r-cran-cluster 4.0.0-1.1910.1
2 r-cran-survival 4.0.0-1.1910.1
3  r-cran-spatial 4.0.0-1.1910.1
4    r-cran-rpart 4.0.0-1.1910.1
5     r-cran-mgcv 4.0.0-1.1910.1
6   r-cran-matrix 4.0.0-1.1910.1
R> 
```

Yes, and outside Docker is absolutely forbidden for user-level (CRAN-style) package to write to `/etc` and `/usr`.  Simply cannot do.

**Comment by Enchufa2** [comment]
And how do you filter out packages that depend on r-base-core but are not R packages (including R subpackages; e.g., in Fedora, R-devel depends on R-core)?

> Yes, and outside Docker is absolutely forbidden for user-level (CRAN-style) package to write to `/etc` and `/usr`. Simply cannot do.

Completely agree, but I never intended this to be a user-level CRAN-style package, but a system-level package that is provided by your distribution, just as R itself. And that's why requiring to set a prefix (or prefixes) was a good idea to me: it forces the distro packager to think about what they want to allow the useR to do.

**Comment by eddelbuettel** [comment]
> how do you filter out packages that depend on r-base-core but are not R packages

`grepl()` after getting the vector. I think a regexp `r-(cran|bioc|other|omegahat)-*` will hit 99.9% of the cases. I think I have a use case in a write up on github...

> never intended this to be a user-level CRAN-style package

Yep!

**Comment by eddelbuettel** [comment]
This is where I had a running log of tasks a few years ago:

https://eddelbuettel.github.io/rcppapt/binnmuAfterR340.html

**Comment by Enchufa2** [comment]
> > how do you filter out packages that depend on r-base-core but are not R packages
> 
> `grepl()` after getting the vector. I think a regexp `r-(cran|bioc|other|omegahat)-*` will hit 99.9% of the cases. I think I have a use case in a write up on github...

So that was my point: at the end of the day, you do need those prefixes, right? :) So why the revdep in the first place?

**Comment by eddelbuettel** [comment]
To _learn_ them.  To overcome a fixed set.  In practice I'd use `r-(.*)-(.*)` and check the middle term (to exclude "doc" as I ship `r-doc-html`).  Otherwise the whole point of the `revdep` is to learn what a fixed expression will not know.

**Comment by Enchufa2** [comment]
Ok, so we definitely wouldn't want to launch this discovering process every time `install` or `remove` are called. That can be easily done once if a certain configuration file is not present. But then, if a new repo with more R packages with another prefix is added, the user should be able to say, ok, maybe it's time to re-discover. Otherwise, there's no difference with current behaviour.

For that, first of all, a function would be needed [here](https://github.com/Enchufa2/bspm/blob/devel/inst/service/backend/apt.py), called e.g. `discover`, that would take no arguments and would return a list of valid prefixes. Could you work on that for APT? I'll work on the DNF counterpart, and then we can expose that to the user.

Also, this solution would still allow a sysadmin to hardcode certain prefixes and prevent exposing the `discover` method. Sounds good?

**Comment by eddelbuettel** [comment]
>  every time `install`

Related:  Calling `apt update` each time is weird.  Is there a way to suppress it?  (I know _nothing_ about `python3-apt`.  There is in command-line apt because if your cache is current, then `apt install foo` gets you the right foo, no need to update first).

I think getting a list of plausible package name patterns could go along with updating the indices. It really is just metadata.  And when the user then call `install.packages(c("foo", "bar"))` we can check these are known as `r-cran-foo` or `r-bioc-for` or ... given the recently updated package "pattern" map.

**Comment by Enchufa2** [comment]
Yeap, I mean, I'm not really familiar with APT. I just got it working with this naive approach, but for sure cache management and also reporting (the output looks weird in a docker container, not sure why) can be improved. One idea would be to update cache only in this `discover` function. Or maybe there's a way to retrieve how old the cache is to take a decision upon `install`?

**Comment by eddelbuettel** [comment]
Yup, had similar thoughts.  Maybe a helper function as part of `bspm` which "refreshes" or "updates" or "discovers"...

**Comment by Enchufa2** [comment]
I opened separate issues for cache management #4 and output in docker #5.

**Comment by Enchufa2** [comment]
[Simplified installation](https://github.com/Enchufa2/bspm/blob/devel/README.md#installation). I've implemented the required infrastructure for the discovery mechanism, exposed via `bspm::discover()`. The last piece remaining is to implement the logic to dynamically discover those prefixes and exclusions, [here](https://github.com/Enchufa2/bspm/blob/devel/inst/service/backend/apt.py#L4-L8) and [here](https://github.com/Enchufa2/bspm/blob/devel/inst/service/backend/dnf.py#L7-L12).

**Comment by eddelbuettel** [comment]
Hah. I was hacking on (likely) similar aspects.  (Ignore that I left the r-cran-* stanza):

```sh
edd@rob:~/git/bspm(feature/simpler_config)$ wajig install /var/cache/pbuilder/result/r-cran-bspm_0.3.1-1_all.deb 
Selecting previously unselected package r-cran-bspm.
(Reading database ... 498555 files and directories currently installed.)
Preparing to unpack .../r-cran-bspm_0.3.1-1_all.deb ...
Unpacking r-cran-bspm (0.3.1-1) ...
Setting up r-cran-bspm (0.3.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
edd@rob:~/git/bspm(feature/simpler_config)$ 
```

The package is (should be, haven't done mich testing) self-describing.

**Comment by eddelbuettel** [comment]
And works as expected.  It helps to have an `apt` config file setting recommends to false (which my Docker container here did not have so I added it).  Also enabled `bspm`, of course.  Then:

```sh
root@4b60420794aa:/work# dpkg -i r-cran-bspm_0.3.1-1_all.deb                 # (re)install bspm
(Reading database ... 19020 files and directories currently installed.)                                                                                                                                            
Preparing to unpack r-cran-bspm_0.3.1-1_all.deb ...                                                      
Unpacking r-cran-bspm (0.3.1-1) over (0.3.1-1) ...
Setting up r-cran-bspm (0.3.1-1) ...                                                                     
root@4b60420794aa:/work# install.r units                                     # test with your units package
(loaded the methods namespace)                                                                           
Loading required package: utils                                                                          
Tracing function "install.packages" in package "utils"                                                                                                                                                             
Installing system packages...                      
Reading package lists... Done                                                                            
Building dependency tree                                                                                                                                                                                           
Reading state information... Done                                                                                                                                                                                  
Hit http://deb.debian.org/debian testing InRelease                                                                                                                                                                 
Hit http://cdn-fastly.deb.debian.org/debian sid InRelease                                                                                                                                                          
Fetched 0 B in 0s (0 B/s)                                                                                                                                                                                         
Reading package lists... Done                                                                                                                                                                                      
Building dependency tree                      
Reading state information... Done                                                                        
Get:1 http://deb.debian.org/debian testing/main amd64 libudunits2-data all 2.2.26-5 [25.8 kB]                                                                                                                     
Get:2 http://deb.debian.org/debian testing/main amd64 libudunits2-0 amd64 2.2.26-5+b1 [57.3 kB]                                                                                                                   
Get:3 http://deb.debian.org/debian testing/main amd64 r-cran-pkgkitten all 0.1.5-2 [23.7 kB]                                                                                                                       
Get:4 http://deb.debian.org/debian testing/main amd64 r-cran-rcpp amd64 1.0.4.6-1+b1 [1951 kB]                                                                                                                     
Get:5 http://deb.debian.org/debian testing/main amd64 r-cran-units amd64 0.6-6-1+b1 [744 kB]                                                                                                                      
Fetched 2802 kB in 0s (0 B/s) 
[....]
```

**Comment by eddelbuettel** [comment]
I guess I could remove `r-cran-*` from the package name and just called it `r-bspm` or something...

**Comment by Enchufa2** [comment]
Indeed. :)

**Comment by eddelbuettel** [comment]
Preferences?

**Comment by Enchufa2** [comment]
`r-bspm` has the advantage that we don't need to add it to exclusions manually.

**Comment by eddelbuettel** [comment]
Counterargument as I was just out cycling for an hour:  we want to be on CRAN. I learned that with `littler`, you get a much wider reach.  We can just add a function that the user needs to run as `sudo` to copy the two files, or even print the shell snippet to screen.  On load we can test if present and if not display a message.

What do you think?

**Comment by Enchufa2** [comment]
I would be more complicated than that. A installation in the user's home is useless. So the whole package would need to install itself under /usr, remove current user's copy and ask the user to reload R. And even then, SELinux-enabled systems would prevent the package from working at all.

**Comment by eddelbuettel** [comment]
What is complicated?  Yesterday I 
- created such a package in a few minutes
- installed it in Docker and used it

**Comment by Enchufa2** [comment]
Inside docker it runs as root, so the Python script is called directly, there's no D-Bus service involved.

**Comment by eddelbuettel** [comment]
We are getting nowhere.  For you "Docker" is something else than it is for me.  I use it as a chroot, as a virtual machine, as a playground to test -- NOT something separate.  I see what you write in your README. For you Docker is a service on a machine.  Not my use case.  So please it what I wrote above as

> What is complicated? Yesterday I
> 
> created such a package in a few minutes
> installed it on a pristime Debian + R machine and used it

**Comment by Enchufa2** [comment]
Forget about docker. The technical issue here is that regular users can't install/remove packages. Docker is just a virtual machine, playground... call it whatever you like, where that issue doesn't exist. Being or not root is the fundamental issue, and means that the layer to allow the user to install system packages gets more convoluted.

So bspm on CRAN would work seamlessly for root users (i.e., typically just inside docker), but would be the following *for the rest of the users*:

```
install.packages("bspm")
bspm::install_sys(something)
# > This package doens't work as a user package, please run:
# > $ sudo apt install r-cran-bspm
# > in a terminal to install it as a system package
```

**Comment by eddelbuettel** [comment]
Yes. This *already* works for me:

1. Create a Debian package r-cran-bspm
2. Install the Debian package
3. Add `bspm::enable()` to `Rprofile.site` (which the package could/should do once more mature, right now user option)
4. Run `install.packages()` as user, have Debian package installed where available.

Point 4 may hinge on the fact that I have `sudo` managed. But that would be the same for other `dpkg` and `apt` uses too.

**Comment by Enchufa2** [comment]
Oh, I forgot, the package should prompt the user to remove the user package too:

```
install.packages("bspm")
bspm::install_sys(something)
# > This package doens't work as a user package, please run:
# > $ sudo apt install r-cran-bspm
# > in a terminal to install it as a system package, then
# > > remove.packages("bspm")
# > in an R session to remove this copy of the package
```

Otherwise, R would be always loading the user package and thus keep prompting the same, right?

That's easy to do. The question is, do you think that bringing this to CRAN is worth it? I mean, you get exposure... to some extent (the exposure was much bigger 10 years ago when there were... 1000 packages on CRAN?), but then the package does nothing when regular users install it from CRAN (which... may be odd for many users?).

**Comment by eddelbuettel** [comment]
The `sudo` issue nags me a little.  

The use case _in controlled environments_ such as Docker or Travis or GH Actions or ... where we have access to root is fantastic though.  Have to think a little if there is a way to get "system installs as user".  Maybe not.   I may have been in haste earlier and what I thought worked on my laptop (as a normal yet sudo-managed) user does not seem to work.  I'll be taking a break now.

**Comment by Enchufa2** [comment]
Coming back to the main topic of this issue, this works to automate the discovery for APT:

```python
def discover():
    import re
    
    cache = apt.Cache()
    cache.update() # cache_update(cache, force=True)
    cache.open()
    pkgs = [x for x in cache.keys() if re.match("^r-(.*)-(.*)", x)]
    prefixes = {"-".join(x.split("-")[0:2]) + "-" for x in pkgs}
    
    return {
        "prefixes": list(prefixes - {"r-doc-", "r-base-"}),
        "exclusions": []
    }
discover()
# {'prefixes': ['r-other-', 'r-cran-', 'r-bioc-', 'r-omegahat-'], 'exclusions': []}
```

where I'm trying to match the procedure you described above.
