### ISSUE TITLE
Does not work inside RStudio 

### ISSUE THREAD

**Issue by raffaem** [Enchufa2/bspm#39]
If you open a script in RStudio, write `library(lib)` where `lib` is a library which is not installed, RStudio will prompt you to install it:

![image](https://user-images.githubusercontent.com/54762742/161283588-4199f5bd-ff68-44b0-9cba-4f1c06ecffd9.png)

but if you click "Install", installation from source is triggered, not the `R-CRAN-*` packages.

**Comment by Enchufa2** [comment]
Yeap, this is a known issue. It works fine if you just call `install.packages` or `update.packages` manually, but RStudio apparently does its own thing when you click "Install" in that message, and bypasses our mechanism to intercept `install.packages`. Any clue on how this could work would be appreciated.

**Comment by raffaem** [comment]
I have opened a question on [RCommunity](https://community.rstudio.com/t/override-what-rstudio-does-when-you-click-install/134788)

**Comment by Enchufa2** [comment]
This is a current limitation: https://github.com/rstudio/rstudio/issues/10945. Unless RStudio allows the system settings to be loaded in the child process, unfortunately there's nothing we can do.

**Comment by kendonB** [comment]
I find that `install.packages` also does not work in RStudio - I get the `cannot connect to the system package manager` error.

**Comment by raffaem** [comment]
> I find that `install.packages` also does not work in RStudio - I get the `cannot connect to the system package manager` error. Works fine running R in the terminal.

I think this is a very different issue than what's discussed here

**Comment by Enchufa2** [comment]
Yes, it's definitely a different issue. Please see closed issues, and open a new one with more details if that didn't solve your problem.

**Comment by Enchufa2** [comment]
This has been addressed in https://github.com/rstudio/rstudio/pull/12176 and listed for the next release of RStudio.

**Comment by Enchufa2** [comment]
And working since release 2022.12.0.
