### ISSUE TITLE
Improve APT cache management

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#4]
DNF manages cache automatically. APT requires updating it from time to time, but currently it's called for every `install` and `remove`. It would be better to save the date of the last update and then invalidate the metadata if e.g. the difference is more than 48 hours (that's what DNF does by default).

**Comment by eddelbuettel** [comment]
I started to have some first looks into [python-apt docs](https://apt-team.pages.debian.net/python-apt/library/apt.package.html). The fact that I don't write much Python does not help much I can poke around a little.   

The _obvious_ first pick is to do it once at package load, and maybe then again _if and when the user asks for it_.

**Comment by Enchufa2** [comment]
I found several threads discussing how to know how old is the metadata. There is no single answer, and they differ for Ubuntu and Debian. So I finally implemented my own very simple cache manager (see the commit above). Basically, it touches a file each time the cache is updated. Then it compares current time with the modification time for that file: if it's more than 48 hours (default DNF behaviour), it updates the cache and re-touches the file.

**Comment by eddelbuettel** [comment]
I guess it's a hard problem in general.  But here maybe we can keep it simpler.  Update the cache when the package loads.  Write down a timestamp, easiest in a package env.  The on "use" (i.e. when installing is needed) check the stored timestamp against current and maybe warn if less than an `options()`-setable threshold: an hour, 30 minutes, ...   If you use `testing` as I do updates are frequent enough that 48 hours is likely too long.  For `stable` it may be different.

**Comment by Enchufa2** [comment]
The motivation of always updating the cache was precisely to keep it as simple as possible. I don't like the idea of exposing system package manager's specifics in the R session.

Aside: I don't like the idea of exposing that in the apt tool either. At the end of the day, what most users see is that `apt update; apt install something` always work while just `apt install something` sometimes doesn't, so they always run the first option just in case.

I don't want the R user to be thinking about the cache at all. And implementing an option to change the invalidation time would substantially complicate the code just for an APT specific. So we either choose a shorter fixed invalidation time, if you think that works best, or we just go back to always calling update but we make it quiet (no output about that).

**Comment by eddelbuettel** [comment]
A common workflow is to a) update and to then do several distinct operations separately.  They only need one update, which is why it is separate command.

**Comment by Enchufa2** [comment]
Then it would be enough to set an invalidation time of... 5 minutes, 10 minutes? So that separate workflows all have their own call to update.

**Comment by eddelbuettel** [comment]
Yes, I like that better, and why I was thinking of an `options()` to set and fine-tune (and/or a separate command).  Seems like a nicer compromise.

The new autodiscovery is very nice.  Well done!  I just tested installation of 'S4Vectors' from BioConductor, and it came in flawlessly bring BiocGenerics with it.  This is working well.  (I still recommend taking out `TextInstallProgress()` as it does not play well with `apt` overwriting lines.)
