### ISSUE TITLE
Add a mechanism to retrieve package versions

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#41]
Use case: packages like `renv` could ask `bspm` what's available in the system repos to choose those preferentially if versions match.

**Comment by eddelbuettel** [comment]
For what it is worth, in `r2u` I just use `available.packages()`.

**Comment by Enchufa2** [comment]
What `renv` does, basically, is:

- The lockfile says that `pkgA` v3.1 must be installed.
- `renv` downloads cran.r-project.org/src/contrib/Archive/pkgA/pkgA_3.1.tar.gz
- installs it in the cache, and links it in the project repository.

It also implements a cache, etc. And `pak` is _basically_ the same with more bells and whistles. With this feature, this could be possible:

- The lockfile says that `pkgA` v3.1 must be installed.
- `renv` asks `bspm` what version is available for `pkgA`. This could be the latest one (it would normally be the latest one), but it could be an old one if `r2u` (or `c2d4u4`, or whatever) is not up-to-date for some reason. So `available.packages` is not 100% reliable here.
- If the version returned by `bspm` is 3.1, then `renv` just calls `bspm::install_sys("pkgA")`
- and links it in the project repository.

Of course, if the version returned by `bspm` is not 3.1, then `renv` can proceed as usual.

**Comment by eddelbuettel** [comment]
> So `available.packages` is not 100% reliable here.

You are correct. I use that on the building side to find what I could inject into `r2u`.  On the other side we could possibly use `RcppAPT` :)  but it is probably simpler to just ask `apt` or `dpkg` from Python.

**Comment by jranke** [comment]
> Use case: packages like `renv` could ask `bspm` what's available in the system repos to choose those preferentially if versions match.

Another use case for having the R package versions available in the binary repos that bspm accesses, would be to have `install.packages()` use the latest version. I was actually assuming this (eddelbuettel/r-ci#10)...
