### ISSUE TITLE
littler always installs @HEAD in bspm?

### ISSUE THREAD

**Issue by mpadge** [Enchufa2/bspm#42]
Not sure whether this is the right place to try to debug this issue or not? @eddelbuettel As you know, we @rOpenSci have build an internal package-checking system on bspm, for which we are very grateful indeed! I need to temporarily change one GitHub installation to a non-default branch, so simply used a `org/repo@branch` call to a (`littler`) `installGithub.r` call. The problem is when the Dockerfile builds, it always grabs `org/repo@HEAD`. I've tried directly calling `remotes::install_github("org/repo@branch")` in the dockerfile, but that too grabs `@HEAD` instead, so it doesn't appear to be a `littler` problem. I have no idea where to start debugging this issue. The problem only happens when the whole thing is build via `docker-compose`. Sorry for vague description, but I've also no idea at present how to start to debug this. Any help would be appreciated!

**Comment by eddelbuettel** [comment]
The `r` binary embeds an R interpreter. It does not know how to spell 'git' or 'HEAD'.  What you do with it is up to you.

**Comment by mpadge** [comment]
Thanks Dirk, my bad. It was a docker cache issue after all. Cleared the whole thing out and all works as expected.
