### ISSUE TITLE
install.packages() does not respect "repos" param

### ISSUE THREAD

**Issue by mpadge** [Enchufa2/bspm#44]
Inside R in a clean image of rocker/r-bspm:20.04:

``` r
install.packages("StanHeaders", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))
packageVersion("StanHeaders")
#> [1] 2.21.0-7
```

That is from CRAN, and not from the additional repo, which should be 2.26.X. Same thing happens for any attempts to install other packages from other repos. This only happens in BSPM; in other rocker containers the "repos" param works as expected. Any help would be greatly appreciated!

**Comment by eddelbuettel** [comment]
Yes but how could it?

BSPM's whole stick is to take a request for an R package and to then _BAM!_ pull the rug under you and give it to you as a .deb binary from an apt repo.  So seems like par for the course, if arguably not all that well documented.

**Comment by eddelbuettel** [comment]
And it works just fine in the `r2u` container (which has `bsmp` "on" by default) if I just start with `bspm::disable()`.
