### ISSUE TITLE
no package called bspm in ubuntu WSL

### ISSUE THREAD

**Issue by rdataforge** [Enchufa2/bspm#50]
Managed to successfully execute script for ubuntu (WSL) located here 
https://github.com/eddelbuettel/r2u/blob/master/inst/scripts/add_cranapt_focal.sh

After executing script line by line and after adding keys one by one using the procedure from the link here:

https://unix.stackexchange.com/questions/399027/gpg-keyserver-receive-failed-server-indicated-a-failure/399091#399091
Now. When starting R i get:

```

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in loadNamespace(x) : there is no package called ‘bspm’
```

opened command line and issued:

` sudo Rscript -e 'install.packages("bspm", repos="https://cran.r-project.org")'`

And i get:

```
[sudo] password for rdata:
Available system packages as root...
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit http://archive.ubuntu.com/ubuntu focal InRelease
Hit https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Hit http://ppa.launchpad.net/marutter/rrutter4.0/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Hit http://ppa.launchpad.net/neovim-ppa/stable/ubuntu focal InRelease
Ign https://dirk.eddelbuettel.com/cranapt focal InRelease
Hit https://dirk.eddelbuettel.com/cranapt focal Release
Ign https://r2u.stat.illinois.edu/ubuntu focal InRelease
Hit https://r2u.stat.illinois.edu/ubuntu focal Release
Fetched 336 kB in 0s (0 B/s)
Install system packages as root...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Fetched 0 B in 0s (0 B/s)
```

Then again I open R:

`Error in loadNamespace(x) : there is no package called ‘bspm’`

**Comment by eddelbuettel** [comment]
Make sure `.libPaths()` is identical for the root and and normal user. If in doubt set a `lib` argument to `install.packages`.

**Comment by rdataforge** [comment]
Removed call to bspm::..... from Rprofile and executed using libpath both as root and as user.

As root worked installation, As user I was forced to choose a personal library instead but to no avail.
```

> install.packages("bspm", lib="/home/rdata/R/x86_64-pc-linux-gnu-library/4.2")
trying URL 'https://packagemanager.rstudio.com/all/__linux__/focal/latest/src/contrib/bspm_0.4.0.tar.gz'
Content type 'binary/octet-stream' length 34667 bytes (33 KB)
==================================================
downloaded 33 KB

Error in loadNamespace(x) : there is no package called ‘bspm’
Calls: suppressMessages ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

The downloaded source packages are in
        ‘/tmp/RtmpwewUz5/downloaded_packages’
Warning message:
In install.packages("bspm", lib = "/home/jose/R/x86_64-pc-linux-gnu-library/4.2") :
  installation of package ‘bspm’ had non-zero exit status
```

**Comment by eddelbuettel** [comment]
It is is documented that you must run it as root (hence the `sudo R CMD INSTALL ...`) to access the system commands.

**Comment by rdataforge** [comment]
that is my point. No matter if I run as root or as normal user. I get always the same issue as seems that: 1. is not installing anything.


 ~  sudo Rscript -e 'install.packages("bspm", repos="https://cran.r-project.org")'                                                                                                         ✔  took 4m 15s    base    at 19:03:20   
Available system packages as root...
Hit http://archive.ubuntu.com/ubuntu focal InRelease
Hit http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit http://security.ubuntu.com/ubuntu focal-security InRelease
Hit https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease
Hit http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Hit http://ppa.launchpad.net/marutter/rrutter4.0/ubuntu focal InRelease
Hit http://ppa.launchpad.net/neovim-ppa/stable/ubuntu focal InRelease
Ign https://dirk.eddelbuettel.com/cranapt focal InRelease
Hit https://dirk.eddelbuettel.com/cranapt focal Release
Ign https://r2u.stat.illinois.edu/ubuntu focal InRelease
Hit https://r2u.stat.illinois.edu/ubuntu focal Release
Fetched 0 B in 0s (0 B/s)
Install system packages as root...
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Fetched 0 B in 0s (0 B/s)

~  R                                                                                                                                                                                         ✔  took 43s    base    at 19:04:18   

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in loadNamespace(x) : there is no package called ‘bspm’

**Comment by eddelbuettel** [comment]
Still circular.  You start from `install.packages()` and _you see apt outcome_ so _clearly_ `bspm` is dispatching.

Which in turn implies `bspm` is installed which makes installing it a null-op as it is already there.

**Comment by Enchufa2** [comment]
So the question still is what is the output from `.libPaths()` when you execute R as root vs. as normal user.

**Comment by rdataforge** [comment]
user lib:
/home/rdata/R/x86_64-pc-linux-gnu-library/4.2

root lib:
/root/R/x86_64-pc-linux-gnu-library

Started again with a new fresh WSL installation to see if library could be shared between root and user to no avail. Permission denied and prompted to use a personal library instead

**Comment by eddelbuettel** [comment]
Please show us the _complete_ result of

```sh
Rscript -e 'print(.libPaths())'
```

on either.   What you showed is likely only partial, yet the reason for your woes (if it is the first).  You set up per-user path on your system, you get per-user path and _by construction they are different_.   I happen to not like them so for me on this main work machine:

```sh
$ Rscript -e 'print(.libPaths())'
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"       "/usr/lib/R/library"           
$ 
```

**Comment by Enchufa2** [comment]
This seems to be a local configuration error, not a bspm issue. Closing here, but let us know if we can help further.
