### ISSUE TITLE
ImportError: no suitable backend found

### ISSUE THREAD

**Issue by LiNk-NY** [Enchufa2/bspm#53]
Hi Iñaki, @Enchufa2 

I running into this error when running the following command on our `bioconductor/bioconductor_docker:devel` container. 
```r
> install.packages("cli")
Error: cannot connect to the system package manager
```

Is there something that is required by `bspm` that is not part of [add_cranapt-jammy.sh](https://github.com/waldronlab/MultiAssayWorkshop/blob/devel/inst/scripts/add_cranapt_jammy.sh) to make the set up functional on an independent container? 

I am using this [Dockerfile](https://github.com/waldronlab/MultiAssayWorkshop/blob/devel/Dockerfile):

```docker
FROM bioconductor/bioconductor_docker:devel
WORKDIR /home/rstudio
COPY --chown=rstudio:rstudio . /home/rstudio
ENV R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
ENV CRAN='https://packagemanager.rstudio.com/cran/__linux__/jammy/latest'
COPY inst/scripts /home/rstudio/scripts
RUN bash ./scripts/add_cranapt_jammy.sh
RUN sudo R -f ./scripts/install_deps.R ## errors here
```

[install_deps.R](https://github.com/waldronlab/MultiAssayWorkshop/blob/devel/inst/scripts/install_deps.R) is a simple script that invokes the installation of packages needed for the workshop:

```r
BiocManager::install(update = TRUE, ask=FALSE)
remotes::install_local(
    dependencies = TRUE,
    repos = BiocManager::repositories(),
    build_vignettes = TRUE
)
```

## Debugging 

I was able to build the Docker container without the last command in the Dockerfile above and patch into the container and run the package installation command. This is the error produced from within `bspm:::root_call` after slight modification of the `stderr` argument:

```
Traceback (most recent call last):
  File "/usr/local/lib/R/site-library/bspm/service/bspm.py", line 3, in <module>
    import backend
  File "/usr/local/lib/R/site-library/bspm/service/backend/__init__.py", line 15, in <module>
    raise ImportError("no suitable backend found")
ImportError: no suitable backend found
```

**Comment by Enchufa2** [comment]
[This line](https://github.com/waldronlab/MultiAssayWorkshop/blob/85589ddf49c4216466c7b65eadee70945a6418e6/inst/scripts/add_cranapt_jammy.sh#L35) requires a `-y`. The same bug is present [upstream](https://github.com/eddelbuettel/r2u/blob/c333ec42bc16dcda4596a60b645685db4bcf8485/inst/scripts/add_cranapt_jammy.sh#L33), but probably the base image @eddelbuettel uses already has the required packages installed.

**Comment by eddelbuettel** [comment]
Actuallty, and while I could be wrong, I do not believe these BioConductor Docker images share any lineage with mine.  As such maybe @LiNk-NY wants to use mine as baselines or comparison benchmarks possibly providing existence proofs.

**Comment by LiNk-NY** [comment]
Hi Iñaki @Enchufa2 and Dirk @eddelbuettel, 
Thank you for the `-y` tip! It worked. 
The Bioconductor images are descendants of the `rocker/rstudio` ones which as you may know include `pandoc` and other tools. For now, I can work with this layer provided by your script and wait until the `r2u` tooling has been integrated to the rocker images. I will certainly use your image for comparison benchmarks. Thanks!

**Comment by eddelbuettel** [comment]
Not rocker/rstudio is based on the _versioned_ stack and that is fundementally incompatible with r2u.

We can (trivially) add the rstudio .deb to the other r2u or c2d4u based (non-RSPM) stacks.

**Comment by Enchufa2** [comment]
> I do not believe these BioConductor Docker images share any lineage with mine. 

Correct, and that's why yours is working even if the command is incomplete: your base image already has `python3-apt` installed.

**Comment by eddelbuettel** [comment]
Yes and no. 'Base image' really is rocker/r-base aka r-base and it does not.

r2u of course as it is bspm based, as is rocker/r-bspm (currently still using c2d4u, to be cleaned up).

To me, "base image" is still r-base as it is my fundamental building block (with Debian) and not part of the versioned stack (using Ubuntu and RSPM/PPM).

**Comment by Enchufa2** [comment]
Closing here, fix sent as the PR above.
