### ISSUE TITLE
Debian (bullseye) docker: D-Bus service not found, cannot connect to the system package manager

### ISSUE THREAD

**Issue by bsiranosian** [Enchufa2/bspm#55]
Hello, thank you for your work on this tool, which looks really useful!

I'm trying to incorporate `bspm` into a docker container, which is based on `docker.io/debian:bullseye-slim`. I've enabled the `bullseye-cran40/` apt repository and installed R 4.2.2 from there. I then install `bspm` as follows:

```
sudo apt update -y \
    && sudo apt install -y --no-install-recommends \
        python3-apt \
        python3-dbus \
        python3-gi \
    && sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' \
    && echo "suppressMessages(bspm::enable())" | sudo tee -a /etc/R/Rprofile.site \
    && echo "options(bspm.sudo=TRUE)" | sudo tee -a /etc/R/Rprofile.site
```
R is running within RStudio server as a non-root user that has sudo access without a password. bspm is enabled on R startup, and the sudo option is properly loaded. The behavior is the same launching R from the terminal. 

However, I get the warning on startup:
```
Warning message:
D-Bus service not found!

- If you are in a container environment, please consider adding the
...
```

Trying to install a package fails like so:
```
> install.packages('survival')
Get:1 http://cloud.r-project.org/bin/linux/debian bullseye-cran40/ InRelease [4367 B]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]                  
Get:3 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:4 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]         
Get:5 http://cloud.r-project.org/bin/linux/debian bullseye-cran40/ Packages [36.2 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]       
Get:7 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [214 kB]
Get:8 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]
Fetched 8660 kB in 6s (1358 kB/s)                                               
Available system packages as root...

  There is a binary version available but the source version is later:
         binary source
survival  3.4-0  3.5-0

Do you want to install later versions from sources? (Yes/no/cancel) no
Install system packages as root...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Error in install.packages : cannot connect to the system package manager
```

Other things I've tried
 * installing from source github release
 * installing various `dbus-*` packages

**Comment by eddelbuettel** [comment]
If I may ask from the sidelines given that I have been looking after R for Debian (and hence Ubuntu) for 20+ years:

- Why Debian?  We have ~1000 packages in the distro, which is way less than the 6k say Michael has in its c2d4u for Ubuntu or of course the 19k packages I have in [r2u](https://eddelbuettel.github.io/r2u/)
- Why debian-slim?  Adding R does not add _that much_ but it is still more than you save via slim and the removal, say, of a few manpages
- Could you please try plain Debian?  Among the support for `bspm` we _do_ offer a pre-made container [via this Dockerfile](https://github.com/rocker-org/bspm/blob/master/testing/Dockerfile) so _ex ante_ if you stray away you may own the bug experienced via that route...)

**Comment by bsiranosian** [comment]
Hi Dirk, 

This container is part of a suite of apps that are exposed to users of a cloud computing system. We've standardized around using debian-slim as the initial source, but I do get the benefits of using ubuntu or another distro. So changing that would be a larger conversation!

Trying with plain `debian:bullseye` results in the same behavior. 

After filing this issue, I went to make a small reproducible example with debian-slim and R/bspm installed the same way. I get the warning on startup, but `bspm` DOES function as expected. There must be something in my configuration that is messing with the functionality. I'll dig further. 

Thanks!

**Comment by eddelbuettel** [comment]
> Trying with plain debian:bullseye results in the same behavior.

We'll take a look. @Enchufa2 is very much on top of this, and nudges me as needed.  He has been so good at this that I never really needed to look deep inside `bspm`.  It will likely be something trivial.

The Debian / Ubuntu mismatch hurts me a little inside too, but there is only so and so much one can do.  Michael ran with some earlier work by myself and others and used Launchpad to get to 6k package.  (Inaki and Detlef proved for Fedora and OpenSUSE that one can go further.)  I eventually had the insight of building on top of RSPM/PPM so now I have 20k packages (for both Ubuntu 20.04 and 22.04) read for `apt` with full-dependency resolution -- and thanks to `bspm` also from an R prompt.  It's good, and it is getting more popular.  I can't say whether it will fit your setup but as Debian and Ubuntu are close it may, also for things like UDF runners etc.

**Comment by Enchufa2** [comment]
@bsiranosian In container environments, bspm works in root or sudo mode, because there's no systemd in there. This is just a warning to help with some possible misconfigurations, but as you showed, the package works fine.

You can safely ignore the warning, or, as the warning itself says, you can add `options(bspm.sudo = TRUE)` to your Rprofile to silence it, but it's not required.

**Comment by Enchufa2** [comment]
Oh, wait, I didn't see the last error. Well, the package is working, because you are clearly calling apt, so it's some repo error. Maybe if you direct us to your dockerfile we could take a look.

**Comment by eddelbuettel** [comment]
On a whim, also please consider what we document in the `r2u` repo / docs: "sometimes" Docker seems to need the additional option `--security-opt seccomp=unconfined` in its call.  Where/why is a little unclear, it seems to be an interaction between host OS and `docker` binary.  It clearly affected me on Ubuntu 22.04, it no longer seems to bite on 22.10.

**Comment by Enchufa2** [comment]
BTW @eddelbuettel did you see the `Error in install.packages : cannot connect to the system package manager` above? The package is working but we don't know what's the specific error. Too bad. That's what #54 fixed. ;-)

**Comment by eddelbuettel** [comment]
Yes but I think that is what I saw too when I didn't escalate security rights.  Uid zero alone didn't do it, `docker` also wanted extra powers.  From (foggy) memory it was the same error.

**Comment by bsiranosian** [comment]
[Dockerfile.txt](https://github.com/Enchufa2/bspm/files/10418825/Dockerfile.txt)

Hi, I was able to create a minimal reproducible error for this bug. See the attached dockerfile. 

Try the above configuration, and then try by changing line 33 to `r-base`. It then builds successfully (at least on my machine). So, some additional package pulled in by `r-base-dev` is messing with the package manager configuration? I'm admittedly at the limits of my debugging ability.

**Comment by eddelbuettel** [comment]
But r-base is a superset bringing in r-base-core, r-base-dev along with documentation packages.

**Comment by bsiranosian** [comment]
Ah I was assuming `r-base-dev` was the larger package. So `r-base` includes something necessary for this to work?

**Comment by eddelbuettel** [comment]
I am not quite sure.  It could be that the development tools and libraries brought in by r-base-dev (which r-base will pull in, but the narrow "just the R interpreter and base packages" r-base-core does not.  

If you ever have to compile from source (which is likely) you want `r-base-core r-base-dev`  which `r-base`  gets you (plus docs etc).

**Comment by Enchufa2** [comment]
The dockerfile above builds just fine for me. It compiles the package, because there's a source version of the survival package that is newer than the binary one. So:

1. If you change `r-base-dev` with `r-base`, you are not installing the development tools, so the source version of the survival package cannot be installed, and the build fails.
2. If you always prefer binary packages over source packages, even if there are newer source versions available, then you need to set `options(install.packages.compile.from.source="never")`, as documented in `?install.packages`.
3. If you want to silence the warning, you need to set `options(bspm.sudo=TRUE)` **before** enabling bspm.
4. Unrelated, but in docker containers, you don't need to install `python3-gi` and `python3-dbus`. You'll save a few bytes.

Putting everything together, the last two chunks of your dockerfile (without the mounts) would be:

```docker
RUN sudo apt update -y \
    && sudo apt install -y \
        python3-apt \
    && sudo Rscript --vanilla -e 'install.packages("bspm", repos="https://cran.r-project.org")' \
    && echo "options(bspm.sudo=TRUE)" | sudo tee -a /etc/R/Rprofile.site \
    && echo "options(install.packages.compile.from.source='never')" | sudo tee -a /etc/R/Rprofile.site \
    && echo "suppressMessages(bspm::enable())" | sudo tee -a /etc/R/Rprofile.site

RUN R -e 'install.packages("survival")'
```

and you're good to go.

**Comment by eddelbuettel** [comment]
(Apologies for my shallow debugging but @Enchufa2 saves our common bacon here.  Just as a postscriptum, allow me to once again toot my #r2u horn (and thanks for your star there...) as it adds new packages "directly" whereas my Debian package for `survival` is still in Debian unstable for the usual few days before (usually automagically) transferring to Debian testing.  Some of my Docker containers point to unstable to skip that step...   In short a fair amount of inside baseball that simply gets learned by doing.  Glad to know you're good now either way.)

**Comment by bsiranosian** [comment]
Thanks @Enchufa2, I see I'm mixing up a few things regarding the compilation from source or not. 

The container builds now and the warning message is gone on R startup. 

Can you try starting the built container and doing an `install.packages` call from within an interactive R session? That's still failing for me.

**Comment by Enchufa2** [comment]
I did, and it works fine for me (without all the `--mount`, so I'm not testing your mounts...).

**Comment by bsiranosian** [comment]
Alright! I appreciate all your help. 

Removing the cache mount from the RUN installing `bspm` has fixed the problem. I was using that to speed up apt installs as I've been rebuilding many containers.... 

I hope this helps anyone who encounters the same frustrating issue.
