### ISSUE TITLE
To CRAN or not to CRAN

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#8]
See #3 for some initial discussion on this. Does bringing this package to CRAN make sense? Exposure there vs. the fact that it doesn't work for *regular* (i.e. non-root) users. They would need to be prompted to install it from system repos.

**Comment by eddelbuettel** [comment]
CRAN is _the_ main repo.  "Use" by users is just one use case, use by CI environments, reproducible setups etc is another and for that we already work.  Plus, we may opt into using `sudo` [1].   I say ship it.


[1] On Debian/Ubuntu I have been using `wajig` by [Graham Williams](https://togaware.com/about/graham-williams/) for well over a decade. One of many little key "UI" advantages it brings:  it calls `sudo` for me, and that makes the smoothest operation.  We could just opt into `sudo busctl ...` as an option. If I find time I'll experiment.

**Comment by Enchufa2** [comment]
The install/remove method dispatch could go as follows:

´´´
if (root())
  return(call_directly())

if (dbus_service_alive())
  return(call_via_dbus())

if (interactive())
  return(call_via_sudo())

warning("could not connect the package manager")
´´´

**Comment by eddelbuettel** [comment]
That is very promising.  I think I could foresee `sudo` uses that are not interactive.  How about the 3rd being

```r
if (getOption("bspm.useSudo", FALSE))
   return(call_via_sudo())
```

Better?  Some combination, maybe an `OR` ?

**Comment by Enchufa2** [comment]
Ok, I'm convinced. Current version falls back on using:

- `sudo` in interactive terminal sessions, or non-interactive sessions if `options(bspm.sudo=TRUE)` is specified.
- `pkexec` in interactive non-terminal sessions (e.g., in RStudio or other GUIs, where plain `sudo` doesn't work). I checked, and it's safe to assume that `pkexec` is installed in every distro with some desktop environment installed (it's part of Freedesktop's PolicyKit).

I'll submit it to CRAN in a few days if we don't find any bugs in the meantime.

**Comment by eddelbuettel** [comment]
This can be closed.
